eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
spring:
  application:
    name: service-hystrix-feign
feign:
  hystrix:
    enabled: true  //feign自带hystrix，不过需要周手动开启