server:
  port: 8081
spring:
  application:
    name: register-center
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka
    fetch-registry: true   #开启服务注册中心的
  instance:
    hostname: peer2